# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jakewendt-ccls_engine}
  s.version = "0.2.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["George 'Jake' Wendt"]
  s.date = %q{2010-10-19}
  s.description = %q{longer description of your gem}
  s.email = %q{github@jake.otherinbox.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "app/controllers/documents_controller.rb",
     "app/controllers/javascripts_controller.rb",
     "app/controllers/locales_controller.rb",
     "app/controllers/pages_controller.rb",
     "app/controllers/photos_controller.rb",
     "app/controllers/roles_controller.rb",
     "app/controllers/stylesheets_controller.rb",
     "app/controllers/user_invitations_controller.rb",
     "app/controllers/users_controller.rb",
     "app/models/document.rb",
     "app/models/page.rb",
     "app/models/page_sweeper.rb",
     "app/models/photo.rb",
     "app/models/role.rb",
     "app/models/user_invitation.rb",
     "app/models/user_invitation_mailer.rb",
     "app/models/user_session.rb",
     "app/views/documents/_document.html.erb",
     "app/views/documents/_form.html.erb",
     "app/views/documents/edit.html.erb",
     "app/views/documents/index.html.erb",
     "app/views/documents/new.html.erb",
     "app/views/documents/preview.html.erb",
     "app/views/javascripts/cache_helper.js.erb",
     "app/views/layouts/application.html.erb",
     "app/views/pages/_child.html.erb",
     "app/views/pages/_form.html.erb",
     "app/views/pages/_page.html.erb",
     "app/views/pages/edit.html.erb",
     "app/views/pages/index.html.erb",
     "app/views/pages/new.html.erb",
     "app/views/pages/show.html.erb",
     "app/views/pages/translate.js.erb",
     "app/views/photos/_form.html.erb",
     "app/views/photos/_photo.html.erb",
     "app/views/photos/edit.html.erb",
     "app/views/photos/index.html.erb",
     "app/views/photos/new.html.erb",
     "app/views/photos/show.html.erb",
     "app/views/stylesheets/dynamic.css.erb",
     "app/views/user_invitation_mailer/invitation.erb",
     "app/views/user_invitations/new.html.erb",
     "app/views/user_sessions/new.html.erb",
     "app/views/users/_form.html.erb",
     "app/views/users/edit.html.erb",
     "app/views/users/index.html.erb",
     "app/views/users/menu.js.erb",
     "app/views/users/new.html.erb",
     "app/views/users/show.html.erb",
     "config/document.yml",
     "config/photo.yml",
     "config/routes.rb",
     "generators/ccls_engine/USAGE",
     "generators/ccls_engine/ccls_engine_generator.rb",
     "generators/ccls_engine/templates/functional/documents_controller_test.rb",
     "generators/ccls_engine/templates/functional/javascripts_controller_test.rb",
     "generators/ccls_engine/templates/functional/locales_controller_test.rb",
     "generators/ccls_engine/templates/functional/pages_controller_test.rb",
     "generators/ccls_engine/templates/functional/photos_controller_test.rb",
     "generators/ccls_engine/templates/functional/roles_controller_test.rb",
     "generators/ccls_engine/templates/functional/sessions_controller_test.rb",
     "generators/ccls_engine/templates/functional/stylesheets_controller_test.rb",
     "generators/ccls_engine/templates/functional/user_invitations_controller_test.rb",
     "generators/ccls_engine/templates/functional/users_controller_test.rb",
     "generators/ccls_engine/templates/javascripts/jquery-ui.js",
     "generators/ccls_engine/templates/javascripts/jquery.js",
     "generators/ccls_engine/templates/javascripts/jrails.js",
     "generators/ccls_engine/templates/javascripts/pages.js",
     "generators/ccls_engine/templates/javascripts/ucb_ccls_engine.js",
     "generators/ccls_engine/templates/migrations/add_attachments_document_to_document.rb",
     "generators/ccls_engine/templates/migrations/add_attachments_image_to_photo.rb",
     "generators/ccls_engine/templates/migrations/create_documents.rb",
     "generators/ccls_engine/templates/migrations/create_pages.rb",
     "generators/ccls_engine/templates/migrations/create_photos.rb",
     "generators/ccls_engine/templates/migrations/create_roles.rb",
     "generators/ccls_engine/templates/migrations/create_roles_users.rb",
     "generators/ccls_engine/templates/migrations/create_user_invitations.rb",
     "generators/ccls_engine/templates/migrations/create_users.rb",
     "generators/ccls_engine/templates/stylesheets/documents.css",
     "generators/ccls_engine/templates/stylesheets/page.css",
     "generators/ccls_engine/templates/stylesheets/pages.css",
     "generators/ccls_engine/templates/stylesheets/photos.css",
     "generators/ccls_engine/templates/stylesheets/shared.css",
     "generators/ccls_engine/templates/stylesheets/user.css",
     "generators/ccls_engine/templates/stylesheets/users.css",
     "generators/ccls_engine/templates/unit/core_extension_test.rb",
     "generators/ccls_engine/templates/unit/document_test.rb",
     "generators/ccls_engine/templates/unit/page_test.rb",
     "generators/ccls_engine/templates/unit/photo_test.rb",
     "generators/ccls_engine/templates/unit/redcloth_extension_test.rb",
     "generators/ccls_engine/templates/unit/role_test.rb",
     "generators/ccls_engine/templates/unit/user_invitation_mailer_test.rb",
     "generators/ccls_engine/templates/unit/user_invitation_test.rb",
     "generators/ccls_engine/templates/unit/user_test.rb",
     "lib/ccls_engine.rb",
     "lib/ccls_engine/authorization.rb",
     "lib/ccls_engine/controller.rb",
     "lib/ccls_engine/core_extension.rb",
     "lib/ccls_engine/date_and_time_formats.rb",
     "lib/ccls_engine/factories.rb",
     "lib/ccls_engine/factory_test_helper.rb",
     "lib/ccls_engine/file_utils_extension.rb",
     "lib/ccls_engine/helper.rb",
     "lib/ccls_engine/pending.rb",
     "lib/ccls_engine/permissive_controller.rb",
     "lib/ccls_engine/redcloth/formatters/html.rb",
     "lib/ccls_engine/resourceful_controller.rb",
     "lib/ccls_engine/tasks.rb",
     "lib/ccls_engine/user_model.rb",
     "lib/tasks/application.rake",
     "lib/tasks/database.rake",
     "lib/tasks/documentation.rake",
     "lib/tasks/rcov.rake",
     "lib/tasks/ucb_ccls_engine_tasks.rake"
  ]
  s.homepage = %q{http://github.com/jakewendt/ucb_ccls_engine}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{one-line summary of your gem}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<i18n>, ["= 0.3.7"])
      s.add_runtime_dependency(%q<rails>, ["~> 2"])
      s.add_runtime_dependency(%q<activerecord>, ["~> 2"])
      s.add_runtime_dependency(%q<activeresource>, ["~> 2"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 2"])
      s.add_runtime_dependency(%q<actionmailer>, ["~> 2"])
      s.add_runtime_dependency(%q<actionpack>, ["~> 2"])
      s.add_runtime_dependency(%q<jrails>, [">= 0"])
      s.add_runtime_dependency(%q<jakewendt-rails_helpers>, [">= 0"])
      s.add_runtime_dependency(%q<jakewendt-ruby_extension>, [">= 0"])
      s.add_runtime_dependency(%q<chronic>, [">= 0"])
      s.add_runtime_dependency(%q<ruby-hmac>, [">= 0"])
      s.add_runtime_dependency(%q<aws-s3>, [">= 0"])
      s.add_runtime_dependency(%q<ssl_requirement>, [">= 0"])
      s.add_runtime_dependency(%q<ryanb-acts-as-list>, [">= 0"])
      s.add_runtime_dependency(%q<gravatar>, [">= 0"])
      s.add_runtime_dependency(%q<RedCloth>, [">= 0"])
      s.add_runtime_dependency(%q<paperclip>, [">= 0"])
      s.add_runtime_dependency(%q<thoughtbot-factory_girl>, [">= 0"])
      s.add_runtime_dependency(%q<jakewendt-assert_this_and_that>, [">= 0"])
      s.add_runtime_dependency(%q<jakewendt-calnet_authenticated>, [">= 0"])
    else
      s.add_dependency(%q<i18n>, ["= 0.3.7"])
      s.add_dependency(%q<rails>, ["~> 2"])
      s.add_dependency(%q<activerecord>, ["~> 2"])
      s.add_dependency(%q<activeresource>, ["~> 2"])
      s.add_dependency(%q<activesupport>, ["~> 2"])
      s.add_dependency(%q<actionmailer>, ["~> 2"])
      s.add_dependency(%q<actionpack>, ["~> 2"])
      s.add_dependency(%q<jrails>, [">= 0"])
      s.add_dependency(%q<jakewendt-rails_helpers>, [">= 0"])
      s.add_dependency(%q<jakewendt-ruby_extension>, [">= 0"])
      s.add_dependency(%q<chronic>, [">= 0"])
      s.add_dependency(%q<ruby-hmac>, [">= 0"])
      s.add_dependency(%q<aws-s3>, [">= 0"])
      s.add_dependency(%q<ssl_requirement>, [">= 0"])
      s.add_dependency(%q<ryanb-acts-as-list>, [">= 0"])
      s.add_dependency(%q<gravatar>, [">= 0"])
      s.add_dependency(%q<RedCloth>, [">= 0"])
      s.add_dependency(%q<paperclip>, [">= 0"])
      s.add_dependency(%q<thoughtbot-factory_girl>, [">= 0"])
      s.add_dependency(%q<jakewendt-assert_this_and_that>, [">= 0"])
      s.add_dependency(%q<jakewendt-calnet_authenticated>, [">= 0"])
    end
  else
    s.add_dependency(%q<i18n>, ["= 0.3.7"])
    s.add_dependency(%q<rails>, ["~> 2"])
    s.add_dependency(%q<activerecord>, ["~> 2"])
    s.add_dependency(%q<activeresource>, ["~> 2"])
    s.add_dependency(%q<activesupport>, ["~> 2"])
    s.add_dependency(%q<actionmailer>, ["~> 2"])
    s.add_dependency(%q<actionpack>, ["~> 2"])
    s.add_dependency(%q<jrails>, [">= 0"])
    s.add_dependency(%q<jakewendt-rails_helpers>, [">= 0"])
    s.add_dependency(%q<jakewendt-ruby_extension>, [">= 0"])
    s.add_dependency(%q<chronic>, [">= 0"])
    s.add_dependency(%q<ruby-hmac>, [">= 0"])
    s.add_dependency(%q<aws-s3>, [">= 0"])
    s.add_dependency(%q<ssl_requirement>, [">= 0"])
    s.add_dependency(%q<ryanb-acts-as-list>, [">= 0"])
    s.add_dependency(%q<gravatar>, [">= 0"])
    s.add_dependency(%q<RedCloth>, [">= 0"])
    s.add_dependency(%q<paperclip>, [">= 0"])
    s.add_dependency(%q<thoughtbot-factory_girl>, [">= 0"])
    s.add_dependency(%q<jakewendt-assert_this_and_that>, [">= 0"])
    s.add_dependency(%q<jakewendt-calnet_authenticated>, [">= 0"])
  end
end

