# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jakewendt-ccls_engine}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["George 'Jake' Wendt"]
  s.date = %q{2010-10-15}
  s.description = %q{longer description of your gem}
  s.email = %q{github@jake.otherinbox.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "app/controllers/documents_controller.rb",
     "app/controllers/javascripts_controller.rb",
     "app/controllers/locales_controller.rb",
     "app/controllers/pages_controller.rb",
     "app/controllers/photos_controller.rb",
     "app/controllers/roles_controller.rb",
     "app/controllers/stylesheets_controller.rb",
     "app/controllers/user_invitations_controller.rb",
     "app/controllers/users_controller.rb",
     "app/models/document.rb",
     "app/models/page.rb",
     "app/models/page_sweeper.rb",
     "app/models/photo.rb",
     "app/models/role.rb",
     "app/models/user_invitation.rb",
     "app/models/user_invitation_mailer.rb",
     "app/models/user_session.rb",
     "app/views/documents/_document.html.erb",
     "app/views/documents/_form.html.erb",
     "app/views/documents/edit.html.erb",
     "app/views/documents/index.html.erb",
     "app/views/documents/new.html.erb",
     "app/views/documents/preview.html.erb",
     "app/views/javascripts/cache_helper.js.erb",
     "app/views/layouts/application.html.erb",
     "app/views/pages/_child.html.erb",
     "app/views/pages/_form.html.erb",
     "app/views/pages/_page.html.erb",
     "app/views/pages/edit.html.erb",
     "app/views/pages/index.html.erb",
     "app/views/pages/new.html.erb",
     "app/views/pages/show.html.erb",
     "app/views/pages/translate.js.erb",
     "app/views/photos/_form.html.erb",
     "app/views/photos/_photo.html.erb",
     "app/views/photos/edit.html.erb",
     "app/views/photos/index.html.erb",
     "app/views/photos/new.html.erb",
     "app/views/photos/show.html.erb",
     "app/views/stylesheets/dynamic.css.erb",
     "app/views/user_invitation_mailer/invitation.erb",
     "app/views/user_invitations/new.html.erb",
     "app/views/user_sessions/new.html.erb",
     "app/views/users/_form.html.erb",
     "app/views/users/edit.html.erb",
     "app/views/users/index.html.erb",
     "app/views/users/menu.js.erb",
     "app/views/users/new.html.erb",
     "app/views/users/show.html.erb",
     "config/document.yml",
     "config/photo.yml",
     "config/routes.rb",
     "lib/ccls_engine.rb",
     "lib/ccls_engine/authorization.rb",
     "lib/ccls_engine/controller.rb",
     "lib/ccls_engine/core_extension.rb",
     "lib/ccls_engine/date_and_time_formats.rb",
     "lib/ccls_engine/factories.rb",
     "lib/ccls_engine/factory_test_helper.rb",
     "lib/ccls_engine/file_utils_extension.rb",
     "lib/ccls_engine/helper.rb",
     "lib/ccls_engine/pending.rb",
     "lib/ccls_engine/redcloth/formatters/html.rb",
     "lib/ccls_engine/user_model.rb"
  ]
  s.homepage = %q{http://github.com/jakewendt/ucb_ccls_engine}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{one-line summary of your gem}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 2"])
      s.add_runtime_dependency(%q<i18n>, ["= 0.3.7"])
      s.add_runtime_dependency(%q<jrails>, [">= 0"])
      s.add_runtime_dependency(%q<jakewendt-rails_helpers>, [">= 0"])
      s.add_runtime_dependency(%q<jakewendt-ruby_extension>, [">= 0"])
      s.add_runtime_dependency(%q<chronic>, [">= 0"])
      s.add_runtime_dependency(%q<ruby-hmac>, [">= 0"])
      s.add_runtime_dependency(%q<aws-s3>, [">= 0"])
      s.add_runtime_dependency(%q<ssl_requirement>, [">= 0"])
      s.add_runtime_dependency(%q<ryanb-acts-as-list>, [">= 0"])
      s.add_runtime_dependency(%q<gravatar>, [">= 0"])
      s.add_runtime_dependency(%q<RedCloth>, [">= 0"])
      s.add_runtime_dependency(%q<paperclip>, [">= 0"])
      s.add_runtime_dependency(%q<thoughtbot-factory_girl>, [">= 0"])
      s.add_runtime_dependency(%q<jakewendt-assert_this_and_that>, [">= 0"])
      s.add_runtime_dependency(%q<jakewendt-calnet_authenticated>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["~> 2"])
      s.add_dependency(%q<i18n>, ["= 0.3.7"])
      s.add_dependency(%q<jrails>, [">= 0"])
      s.add_dependency(%q<jakewendt-rails_helpers>, [">= 0"])
      s.add_dependency(%q<jakewendt-ruby_extension>, [">= 0"])
      s.add_dependency(%q<chronic>, [">= 0"])
      s.add_dependency(%q<ruby-hmac>, [">= 0"])
      s.add_dependency(%q<aws-s3>, [">= 0"])
      s.add_dependency(%q<ssl_requirement>, [">= 0"])
      s.add_dependency(%q<ryanb-acts-as-list>, [">= 0"])
      s.add_dependency(%q<gravatar>, [">= 0"])
      s.add_dependency(%q<RedCloth>, [">= 0"])
      s.add_dependency(%q<paperclip>, [">= 0"])
      s.add_dependency(%q<thoughtbot-factory_girl>, [">= 0"])
      s.add_dependency(%q<jakewendt-assert_this_and_that>, [">= 0"])
      s.add_dependency(%q<jakewendt-calnet_authenticated>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 2"])
    s.add_dependency(%q<i18n>, ["= 0.3.7"])
    s.add_dependency(%q<jrails>, [">= 0"])
    s.add_dependency(%q<jakewendt-rails_helpers>, [">= 0"])
    s.add_dependency(%q<jakewendt-ruby_extension>, [">= 0"])
    s.add_dependency(%q<chronic>, [">= 0"])
    s.add_dependency(%q<ruby-hmac>, [">= 0"])
    s.add_dependency(%q<aws-s3>, [">= 0"])
    s.add_dependency(%q<ssl_requirement>, [">= 0"])
    s.add_dependency(%q<ryanb-acts-as-list>, [">= 0"])
    s.add_dependency(%q<gravatar>, [">= 0"])
    s.add_dependency(%q<RedCloth>, [">= 0"])
    s.add_dependency(%q<paperclip>, [">= 0"])
    s.add_dependency(%q<thoughtbot-factory_girl>, [">= 0"])
    s.add_dependency(%q<jakewendt-assert_this_and_that>, [">= 0"])
    s.add_dependency(%q<jakewendt-calnet_authenticated>, [">= 0"])
  end
end

