#	This file is here so that the plugin/engine can
#	run standard rails rake tasks.
development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3	
#  database: ":memory:"
test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3
#  database: ":memory:"
production:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/production.sqlite3
#  database: ":memory:"


shared_development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/shared_development.sqlite3	

shared_test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/shared_test.sqlite3

shared_production:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/shared_production.sqlite3

