#DEFAULTS: &DEFAULTS
#  :styles:
#    :full: '900'
#    :large: '800'
#    :medium: '600'
#    :small: '150x50'


<% common = ":attachment/:id/:filename" %>
#>> Rails.root.to_s.split('/')
#=> ["", "var", "lib", "tomcat5", "webapps", "clic", "WEB-INF"]

#>> Rails.root.to_s.split('/')
#=> ["", "Users", "jakewendt", "github_repo", "jakewendt", "ucb_ccls_clic"]

<% 
app_name = ( defined?(RAILS_APP_NAME) ) ? 
	RAILS_APP_NAME :
	Rails.root.to_s.split('/').reject{|x|x ==  "WEB-INF"}.last 
%>

development:
  :path: <%= "#{Rails.root}/development/#{common}" %>
#  <<: *DEFAULTS

test:
  :path: <%= "#{Rails.root}/test/#{common}" %>
#  <<: *DEFAULTS

production:
  #	Set the storage class to RRS which is cheaper than 
  #	the default of STANDARD
  :s3_headers:
    x-amz-storage-class: REDUCED_REDUNDANCY
  # public_read or private
  :s3_permissions: :private
  :storage: :s3
  :s3_protocol: https
  :s3_credentials: <%="#{Rails.root}/config/s3.yml" %>
  :bucket: <%= app_name %>
  #	common has a : as the first char so it needs special care
  #	or the string will magically be turned into a symbol
  #	which isn't what we want
  :path: <%= "\"#{common}\"" %>
  # S3 must have a defined path or will generate
  # "Stack level too deep" errors
#  :path: <%= "/home/tomcat/#{app_name}/:attachment/:id/:filename" %>
#  <<: *DEFAULTS
